### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by rvansa** [aeshell/aesh#310]
Not sure what exactly I pressed when scrolling through command history, but I got this:
```
[hyperfoil]$ Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:422)
	at java.util.ArrayList.get(ArrayList.java:435)
	at org.aesh.readline.history.InMemoryHistory.get(InMemoryHistory.java:89)
	at org.aesh.readline.history.InMemoryHistory.getPreviousFetch(InMemoryHistory.java:119)
	at org.aesh.readline.action.mappings.PrevHistory.accept(PrevHistory.java:37)
	at org.aesh.readline.Readline$AeshInputProcessor.parse(Readline.java:235)
	at org.aesh.readline.Readline$AeshInputProcessor.access$100(Readline.java:174)
	at org.aesh.readline.Readline.readInput(Readline.java:95)
	at org.aesh.readline.Readline.access$1000(Readline.java:57)
	at org.aesh.readline.Readline$AeshInputProcessor.lambda$start$1(Readline.java:324)
	at org.aesh.terminal.EventDecoder.accept(EventDecoder.java:118)
	at org.aesh.terminal.EventDecoder.accept(EventDecoder.java:31)
	at org.aesh.io.Decoder.write(Decoder.java:133)
	at org.aesh.readline.tty.terminal.TerminalConnection.openBlocking(TerminalConnection.java:216)
	at org.aesh.readline.tty.terminal.TerminalConnection.openBlocking(TerminalConnection.java:203)
	at org.aesh.readline.ReadlineConsole.accept(ReadlineConsole.java:235)
	at org.aesh.readline.ReadlineConsole.accept(ReadlineConsole.java:87)
	at org.aesh.readline.tty.terminal.TerminalConnection.init(TerminalConnection.java:153)
	at org.aesh.readline.tty.terminal.TerminalConnection.<init>(TerminalConnection.java:86)
	at org.aesh.readline.tty.terminal.TerminalConnection.<init>(TerminalConnection.java:96)
	at org.aesh.readline.ReadlineConsole.start(ReadlineConsole.java:183)
	at org.aesh.AeshConsoleRunner.start(AeshConsoleRunner.java:115)
	at io.hyperfoil.cli.HyperfoilCli.main(HyperfoilCli.java:116)
```

**Comment by stalep** [comment]
Fixed in next version of aesh-readline.
