### ISSUE TITLE
Deadlock in AeshConsole.

### ISSUE THREAD

**Issue by whitingjr** [aeshell/aesh#346]
I am seeing a Deadlock when using AeshConsole. Manifested when running a Quarkus application in dev mode. Toggling the log levels. An issue [34902](https://github.com/quarkusio/quarkus/issues/34902)  has been created on the Quarkus project to track there also.
 A [jstack dump](https://gist.github.com/whitingjr/d44334446c55823b4ed59edcab23980b) shows in the Deadlock section the following.

```
Java stack information for the threads listed above:
===================================================
"Aesh InputStream Reader":
	at io.quarkus.deployment.console.AeshConsole.write(AeshConsole.java:418)
	- waiting to lock <0x000000047febcf48> (a io.quarkus.deployment.console.AeshConsole)
	at io.quarkus.dev.console.RedirectPrintStream.write(RedirectPrintStream.java:24)
	at io.quarkus.dev.console.RedirectPrintStream.println(RedirectPrintStream.java:129)
	at io.quarkus.deployment.console.ConsoleStateManager.toggleLogLevel(ConsoleStateManager.java:172)
	at io.quarkus.deployment.console.ConsoleStateManager$$Lambda$406/0x00000008003d3040.run(Unknown Source)
	at io.quarkus.deployment.console.ConsoleStateManager$1.accept(ConsoleStateManager.java:73)
	at io.quarkus.deployment.console.ConsoleStateManager$1.accept(ConsoleStateManager.java:46)
	at io.quarkus.deployment.console.AeshConsole.lambda$setup$1(AeshConsole.java:275)
	at io.quarkus.deployment.console.AeshConsole$$Lambda$396/0x00000008003d5840.accept(Unknown Source)
	at org.aesh.terminal.EventDecoder.accept(EventDecoder.java:118)
	at org.aesh.terminal.EventDecoder.accept(EventDecoder.java:31)
	at org.aesh.terminal.io.Decoder.write(Decoder.java:133)
	at org.aesh.readline.tty.terminal.TerminalConnection.openBlocking(TerminalConnection.java:216)
	at org.aesh.readline.tty.terminal.TerminalConnection.openBlocking(TerminalConnection.java:203)
	at org.aesh.readline.tty.terminal.TerminalConnection$$Lambda$394/0x00000008003d6040.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.19/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.19/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java.base@11.0.19/Thread.java:829)
"SIGWINCH handler":
	at org.jboss.logmanager.handlers.WriterHandler.doPublish(WriterHandler.java:53)
	- waiting to lock <0x0000000485b58d50> (a java.lang.Object)
	at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:66)
	at io.quarkus.runtime.logging.LoggingSetupRecorder$7$$Lambda$2125/0x0000000800d2d040.accept(Unknown Source)
	at io.quarkus.deployment.logging.LoggingResourceProcessor$2.accept(LoggingResourceProcessor.java:399)
	at io.quarkus.deployment.logging.LoggingResourceProcessor$2.accept(LoggingResourceProcessor.java:375)
	at io.quarkus.runtime.logging.LoggingSetupRecorder$7.publish(LoggingSetupRecorder.java:565)
	at org.jboss.logmanager.ExtHandler.publishToNestedHandlers(ExtHandler.java:97)
	at io.quarkus.bootstrap.logging.QuarkusDelayedHandler.doPublish(QuarkusDelayedHandler.java:81)
	at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:66)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:327)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:334)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:334)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:334)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:334)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:334)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:334)
	at org.jboss.logmanager.Logger.logRaw(Logger.java:750)
	at org.jboss.logmanager.Logger.log(Logger.java:538)
	at org.aesh.readline.terminal.impl.ExecPty.exec(ExecPty.java:453)
	at org.aesh.readline.terminal.impl.ExecPty.doGetConfig(ExecPty.java:245)
	at org.aesh.readline.terminal.impl.ExecPty.getAttr(ExecPty.java:131)
	at org.aesh.readline.terminal.impl.AbstractPosixTerminal.getAttributes(AbstractPosixTerminal.java:46)
	at org.aesh.readline.tty.terminal.TerminalConnection.getAttributes(TerminalConnection.java:175)
	at org.aesh.terminal.Connection.enterRawMode(Connection.java:152)
	at io.quarkus.deployment.console.AeshConsole.setup(AeshConsole.java:303)
	- locked <0x000000047febcf48> (a io.quarkus.deployment.console.AeshConsole)
	at io.quarkus.deployment.console.AeshConsole.lambda$setup$3(AeshConsole.java:301)
	at io.quarkus.deployment.console.AeshConsole$$Lambda$398/0x00000008003d5040.accept(Unknown Source)
	at org.aesh.readline.tty.terminal.TerminalConnection.lambda$init$2(TerminalConnection.java:137)
	at org.aesh.readline.tty.terminal.TerminalConnection$$Lambda$391/0x00000008003d7440.handle(Unknown Source)
	at org.aesh.readline.terminal.impl.AbstractTerminal.raise(AbstractTerminal.java:70)
	at org.aesh.readline.terminal.impl.PosixSysTerminal.lambda$new$0(PosixSysTerminal.java:45)
	at org.aesh.readline.terminal.impl.PosixSysTerminal$$Lambda$387/0x00000008003d1440.run(Unknown Source)
	at org.aesh.readline.terminal.utils.Signals$1.invoke(Signals.java:58)
	at com.sun.proxy.$Proxy33.handle(Unknown Source)
	at sun.misc.Signal$InternalMiscHandler.handle(jdk.unsupported@11.0.19/Signal.java:198)
	at jdk.internal.misc.Signal$1.run(java.base@11.0.19/Signal.java:220)
	at java.lang.Thread.run(java.base@11.0.19/Thread.java:829)
"SIGWINCH handler":
	at io.quarkus.deployment.console.AeshConsole.write(AeshConsole.java:418)
	- waiting to lock <0x000000047febcf48> (a io.quarkus.deployment.console.AeshConsole)
	at io.quarkus.deployment.console.AeshConsole.write(AeshConsole.java:483)
	at io.quarkus.dev.console.RedirectPrintStream.write(RedirectPrintStream.java:20)
	at org.jboss.logmanager.handlers.UncloseableOutputStream.write(UncloseableOutputStream.java:41)
	at org.jboss.logmanager.handlers.UncloseableOutputStream.write(UncloseableOutputStream.java:41)
	at org.jboss.logmanager.handlers.UninterruptibleOutputStream.write(UninterruptibleOutputStream.java:81)
	at sun.nio.cs.StreamEncoder.writeBytes(java.base@11.0.19/StreamEncoder.java:233)
	at sun.nio.cs.StreamEncoder.implFlushBuffer(java.base@11.0.19/StreamEncoder.java:312)
	at sun.nio.cs.StreamEncoder.implFlush(java.base@11.0.19/StreamEncoder.java:316)
	at sun.nio.cs.StreamEncoder.flush(java.base@11.0.19/StreamEncoder.java:153)
	- locked <0x0000000485b58da8> (a java.io.OutputStreamWriter)
	at java.io.OutputStreamWriter.flush(java.base@11.0.19/OutputStreamWriter.java:251)
	at java.io.BufferedWriter.flush(java.base@11.0.19/BufferedWriter.java:257)
	- locked <0x0000000485b58da8> (a java.io.OutputStreamWriter)
	at org.jboss.logmanager.handlers.WriterHandler.safeFlush(WriterHandler.java:165)
	at org.jboss.logmanager.handlers.WriterHandler.flush(WriterHandler.java:135)
	- locked <0x0000000485b58d50> (a java.lang.Object)
	at org.jboss.logmanager.ExtHandler.doPublish(ExtHandler.java:113)
	at org.jboss.logmanager.handlers.WriterHandler.doPublish(WriterHandler.java:64)
	- locked <0x0000000485b58d50> (a java.lang.Object)
	at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:66)
	at io.quarkus.runtime.logging.LoggingSetupRecorder$7$$Lambda$2125/0x0000000800d2d040.accept(Unknown Source)
	at io.quarkus.deployment.logging.LoggingResourceProcessor$2.accept(LoggingResourceProcessor.java:399)
	at io.quarkus.deployment.logging.LoggingResourceProcessor$2.accept(LoggingResourceProcessor.java:375)
	at io.quarkus.runtime.logging.LoggingSetupRecorder$7.publish(LoggingSetupRecorder.java:565)
	at org.jboss.logmanager.ExtHandler.publishToNestedHandlers(ExtHandler.java:97)
	at io.quarkus.bootstrap.logging.QuarkusDelayedHandler.doPublish(QuarkusDelayedHandler.java:81)
	at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:66)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:327)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:334)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:334)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:334)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:334)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:334)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:334)
	at org.jboss.logmanager.Logger.logRaw(Logger.java:750)
	at org.jboss.logmanager.Logger.log(Logger.java:538)
	at org.aesh.readline.terminal.impl.ExecPty.exec(ExecPty.java:453)
	at org.aesh.readline.terminal.impl.ExecPty.getSize(ExecPty.java:230)
	at org.aesh.readline.terminal.impl.AbstractPosixTerminal.getSize(AbstractPosixTerminal.java:62)
	at org.aesh.readline.tty.terminal.TerminalConnection.size(TerminalConnection.java:288)
	at org.aesh.readline.tty.terminal.TerminalConnection.lambda$init$2(TerminalConnection.java:137)
	at org.aesh.readline.tty.terminal.TerminalConnection$$Lambda$391/0x00000008003d7440.handle(Unknown Source)
	at org.aesh.readline.terminal.impl.AbstractTerminal.raise(AbstractTerminal.java:70)
	at org.aesh.readline.terminal.impl.PosixSysTerminal.lambda$new$0(PosixSysTerminal.java:45)
	at org.aesh.readline.terminal.impl.PosixSysTerminal$$Lambda$387/0x00000008003d1440.run(Unknown Source)
	at org.aesh.readline.terminal.utils.Signals$1.invoke(Signals.java:58)
	at com.sun.proxy.$Proxy33.handle(Unknown Source)
	at sun.misc.Signal$InternalMiscHandler.handle(jdk.unsupported@11.0.19/Signal.java:198)
	at jdk.internal.misc.Signal$1.run(java.base@11.0.19/Signal.java:220)
	at java.lang.Thread.run(java.base@11.0.19/Thread.java:829)

Found 1 deadlock.
```

Aesh version

`2.7`

java version
```
openjdk version "11.0.19" 2023-04-18
OpenJDK Runtime Environment Temurin-11.0.19+7 (build 11.0.19+7)
OpenJDK 64-Bit Server VM Temurin-11.0.19+7 (build 11.0.19+7, mixed mode)

```

**Comment by whitingjr** [comment]
@stalep ^^
